apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: client-autoscaling
  namespace: recurso-gic-85132
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300