apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  namespace: recurso-gic-85132
spec:
  serviceName: mongodb-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        resources:
            requests:
              memory: "96Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
        ports:
        - containerPort: 27017
          name: web
  #       volumeMounts:
  #         - name: pvc
  #           mountPath: /data/db
  # volumeClaimTemplates:
  # - metadata:
  #     name: pvc
  #     namespace: gic-group-6
  #   spec:
  #     accessModes: 
  #       - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 1Gi